### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by sternschnaube** [lucyydotp/pronouns3#13]
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pronouns-fabric'!
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.12.jar:?]
	at net.minecraft.server.Main.main(Main:102) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.1]
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: pronouns:possessiveAdj
	at net.minecraft.util.Identifier.validatePath(Identifier:244) ~[?:?]
	at net.minecraft.util.Identifier.<init>(Identifier:47) ~[?:?]
	at net.lucypoulton.pronouns.fabric.ProNounsFabric.onInitialize(ProNounsFabric.java:24) ~[pronouns-fabric-3.0.0-alpha.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.12.jar:?]
	... 8 more

**Comment by lucyydotp** [comment]
Thanks for reporting this! Fabric hasn't really been getting the attention it deserves lately so getting bug reports for it is amazing.

**Comment by lucyydotp** [comment]
I've fixed this in 144d2431e755d7becceb558092cd46f93007148e, it'll be included in the next release.

**Comment by sternschnaube** [comment]
Thank you 🥳
