### ISSUE TITLE
Server crashes when `store` is missing from old config

### ISSUE THREAD

**Issue by sternschnaube** [lucyydotp/pronouns3#17]
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pronouns-fabric'!
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.12.jar:?]
	at net.minecraft.server.Main.main(Main:102) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.1]
Caused by: net.lucypoulton.pronouns.common.platform.config.InvalidConfigurationException: Missing required value store
	at net.lucypoulton.pronouns.common.platform.config.PropertiesConfig.getValue(PropertiesConfig.java:29) ~[pronouns-fabric-3.0.0-alpha.3.jar:?]
	at net.lucypoulton.pronouns.common.platform.config.PropertiesConfig.reloadConfig(PropertiesConfig.java:61) ~[pronouns-fabric-3.0.0-alpha.3.jar:?]
	at net.lucypoulton.pronouns.fabric.FabricPlatform.<init>(FabricPlatform.java:42) ~[pronouns-fabric-3.0.0-alpha.3.jar:?]
	at net.lucypoulton.pronouns.fabric.ProNounsFabric.onInitialize(ProNounsFabric.java:20) ~[pronouns-fabric-3.0.0-alpha.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.12.jar:?]
	... 8 more

**Comment by Evidentsinger14** [comment]
Seems to be the same as #13 - try updating

**Comment by sternschnaube** [comment]
Hello @Evidentsinger14, thank you. 
I was updating already from "alpha.2" to "alpha.3" - now I encounter this new bug.
If you look carefully, then you will see, that both bugs having a different nature.

**Comment by Evidentsinger14** [comment]
You are right - My apologies. everything except the last 4-5 lines were identical. 

I've attempted to hunt down a potential cause for it, but the only thing I can suggest is checking your configuration and see if  `store = file` is in it. [this](https://github.com/lucyydotp/pronouns3/blob/main/pronouns-common/src/main/resources/pronouns-default.cfg#L8) seems to be what its unable to find.

**Comment by sternschnaube** [comment]
That's how my "pronouns.cfg" config file looks:

![image](https://user-images.githubusercontent.com/120551916/211696540-e9b9fd66-4ad7-4d1b-ab44-bcfcf8b38261.png)

**Comment by lucyydotp** [comment]
Yeah this is a new required config field in alpha.3, it's not capable of migrating the config to new versions yet. I'm getting all the breaking changes like this done now while we're still in alpha

**Comment by sternschnaube** [comment]
Works now, thanks again.
Looking forward to more great updates.

**Comment by lucyydotp** [comment]
> EDIT: I would add a direct link into the config, to the "Stats" section. Don't let people search for it.

Yes that's planned, I just don't have a permanent URL for docs yet.
